### ISSUE TITLE
Auto-Login for Comix Heroes

### ISSUE THREAD

**Issue by OldRon1977** [RuperSama/HentaiHeroesScripts#3]
Hey @RuperSama : is it possible to make this script also work with Comix Heroes?
The auto-logout is kind of aggressive and annoying ;)
I hope this can be implemented :)

**Comment by RuperSama** [comment]
i upload a new version of the login script, please report if you find any type of bug, is working fine with edge and chrome

**Comment by OldRon1977** [comment]
I updated the script and will wait if I get a log-out :)
