### ISSUE TITLE
Comixharem login

### ISSUE THREAD

**Issue by Cronosus** [RuperSama/HentaiHeroesScripts#4]
as in issue [HH:265](https://github.com/Roukys/HHauto/issues/265)

after first "login" theres confirmation window, it remain stucked there

**Comment by RuperSama** [comment]
mmm now i have the same login as HH i dont have more the screen of "continue login as.." try clear your cache maybe you get the new login

**Comment by RuperSama** [comment]
@Cronosus i just fixed a bug that get the login script in bucle, please check the new version :)

**Comment by Cronosus** [comment]
looks fine now
